pref("noscript.autoReload",true);
pref("noscript.ctxMenu",true);
pref("noscript.statusIcon",true);
pref("noscript.sound",true);
pref("noscript.notify",true);
pref("noscript.showAddress",false);
pref("noscript.showDomain",false);
pref("noscript.showBaseDomain",true);
pref("noscript.permanent","googlesyndication.com informaction.com flashgot.net maone.net noscript.net");
pref("noscript.default","chrome: flashgot.net gmail.google.com googlesyndication.com informaction.com maone.net mozilla.org mozillazine.org noscript.net hotmail.com msn.com passport.com passport.net passportimages.com");
pref("noscript.stop",true);
