pref("noscript.autoReload",true);
pref("noscript.ctxMenu",true);
pref("noscript.statusIcon",true);
pref("noscript.sound",false);
pref("noscript.notify",true);
pref("noscript.notify.bottom",true);
pref("noscript.showAddress",false);
pref("noscript.showDomain",false);
pref("noscript.showTemp",true);
pref("noscript.showBaseDomain",true);
pref("noscript.permanent","chrome: resource: googlesyndication.com informaction.com flashgot.net maone.net noscript.net");
pref("noscript.default","chrome: resource: flashgot.net google.com googlesyndication.com informaction.com yahoo.com yimg.com maone.net mozilla.org mozillazine.org noscript.net hotmail.com msn.com passport.com passport.net passportimages.com");
pref("noscript.forbidJava",true);
pref("noscript.forbidFlash",false);
pref("noscript.forbidPlugins",false);
pref("noscript.sound.block","chrome://noscript/skin/block.wav");
pref("noscript.allowClipboard",false);
pref("noscript.pluginPlaceholder","chrome://noscript/skin/icon32.png");
pref("noscript.global",false);

